### ISSUE TITLE
Open-sourcing XState's Docs?

### ISSUE THREAD

**Issue by shawntax** [mattpocock/graph-docs-cli#13]
Hello! First off, thanks for working on this project and sharing it -- it's a really great idea!

In the "Integrations" section of the readme, you mention plans to open-source the way XState's docs turn modules into pages with a custom syntax (I'm guessing that's what https://graph-docs.vercel.app/ is?). Since it looks like you're no longer with Stately, do you have any idea as to when or if this well ever be released?

**Comment by mattpocock** [comment]
No idea! I would love to see them released. That's an issue for XState's core repo itself, so I'll close this issue.
